ボウリング問題の処理書いた
gokana-pppp/sample pull request #1
Opened 2023-02-05 15:08 UTC by gokana-pppp

確認よろしく！！

2023-02-05 15:49 UTC, chillout2san requested changes

2023-02-05 15:49 UTC, chillout2san commented on test.js
> +  for (let i = 0; i < scoreSheet.length; i++) {
プログラミングの世界でソースコードの読みやすさのことを可読性と言います。
for文は少なくともJavaScriptの世界の中では可読性が低いです。
`i < scoreSheet.length`って書いてあリますが、結局配列の長さだけループしたいということが言いたいわけで、そういったケースはforEachを使った方がコードが見やすくなります。
forEachで書き直してみましょう。

https://jsprimer.net/basic/loop/#array-foreach

2023-02-05 15:49 UTC, chillout2san commented on test.js
> +    const isSpare = scoreSheet[i].first !== 10 && scoreSheet[i].first + scoreSheet[i].second === 10
`isTurkey`から`isSpare`までループの度に定義されてしまっています。
全体的に変数宣言、オブジェクト、配列の理解は進んでいますが、関数が全く使われていないのが気になります。
for文の外に出して、5つ全て関数にしてみてください。

例えば`isLastFrame`関数は以下のようになります。(関数はアロー関数で書くことに慣れてください)
```javascript
const isLastFrame = ( frame ) => {
  if ( frame.third !== undefined) {
    return true
  }
  return false
}
```

おまけですが、実は`return true`等書かなくてもこう書くとよりスッキリします。
```javascript
const isLastFrame = ( frame ) => {
  return frame.third !== undefined
}
```

2023-02-26 13:34 UTC, gokana-pppp commented on test.js
> +    const isSpare = scoreSheet[i].first !== 10 && scoreSheet[i].first + scoreSheet[i].second === 10
58から76行目を関数に変更、78行目以降をforEachに変更しました。
確認お願いします。

2023-02-26 15:18 UTC, chillout2san approved these changes
👌

2023-02-26 16:06 UTC, merged